title:        viewpoint
baseurl:      '/viewpoint'
url:          ''
permalink:    pretty
incremental:  false


theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
atom_feed:
  hide: true

webrick:
  headers:
    Access-Control-Allow-Origin: '*'
