title:        nyu-dss/viewpoint
url:          'https://nyu-dss.github.io'
baseurl:      '/viewpoint'
description:  'embeddable iiif viewers from uri params'

permalink:    pretty
incremental:  false
source:       src

webrick:
  headers:
    Access-Control-Allow-Origin: '*'
